### ISSUE TITLE
PARTIALLY STAKING ISSUES

### ISSUE THREAD

**Issue by rhim1002** [Tadpole-finance/TadUniswapLiquidityMining#1]
There are some bugs as follow :
 
I try to stake on tadpole.finance twice
The first one, 6.66282321 LP with power 1x.  Stake at 11pm 
The second one, 1.44714788 LP with power 5x. Stake at 12am (1 hour after the first one)

The bug is : 
1. The total my LP power is **8.10997109 (LP)** >> I think it should be (6,662...+ (5x1.447...)) = **13,8.....**

2. The first reward before I stake is gone (Actually I should get 0,12 tad). When we add new stake. (It start again from 0)

Thankyou Admin.
Hope this bug can be fixed soon

My metamask wallet : 0x2F6E2903E4b4B4E660Bbeb966F1a90fbb3b2D76d

This is the screenshoot :

<img width="1283" alt="Screen Shot 2020-11-14 at 00 22 23" src="https://user-images.githubusercontent.com/74423964/99101872-ccf67180-260f-11eb-9050-677f8c9734db.png">

**Comment by ngkong** [comment]
your current power is suppose to be 7.2357394, is that correct?

![image](https://user-images.githubusercontent.com/22634237/102191383-eaa74700-3eeb-11eb-9baa-5a2365dab6e2.png)

**Comment by rhim1002** [comment]
Hello ngkong and thanks for repplying

Im pretty sure it was correct and thanks for adding that fitur. It makes
more clear now.
