### ISSUE TITLE
the page showing "you don't have active stakes" although I have done LP stake

### ISSUE THREAD

**Issue by HamronHamada** [Tadpole-finance/TadUniswapLiquidityMining#2]
Dear admin

I found some bugs on LP stake tab, I was stake LP but the page still showing you don't have active stakes, I use operating system macOS Big Sur 11.0.1, Browser Google Chrome for mac Version 86.0.4240.198 (Official Build) (x86_64), time checking 07.00 until 13.15 WIB 14-11-2020

attach 1 screen shoot (The Balance is covering for secret and privacy)

thank you 

regards
<img width="1440" alt="Screen Shot 2020-11-14 at 12 51 38" src="https://user-images.githubusercontent.com/74444969/99141253-2300fe80-267c-11eb-9562-7ab3cae1dea3.png">

**Comment by ngkong** [comment]
this bug is fixed, can you confirm?

**Comment by HamronHamada** [comment]
Hi admin... the LP Staking Power look the same and nothing changes, you can check my screen shot, I use the same hardware and software, but I have upgrade my Operating system to Mac OS 11.1

Best regards
<img width="1676" alt="Screen Shot 2020-12-15 at 16 12 10" src="https://user-images.githubusercontent.com/74444969/102196280-470d6500-3ef2-11eb-88e0-cc36182b5877.png">

**Comment by HamronHamada** [comment]
Yes... the bug was fix.. confirm and and close

I appreciate you. thanks in advance

**Comment by HamronHamada** [comment]
this is my wallet address : 0x4D1cBCcAd3F7eBe250Df7785A559255BfE7701Ae
 thanks for all your attention and rewards, regards
