### ISSUE TITLE
staking power does not change after one month LP Staking ends

### ISSUE THREAD

**Issue by HamronHamada** [Tadpole-finance/TadUniswapLiquidityMining#3]
<img width="1559" alt="Screen Shot 2020-12-13 at 22 35 16" src="https://user-images.githubusercontent.com/74444969/102017176-deaa7080-3d97-11eb-87cd-0ffefc7ce797.png">
staking power does not change after one month staking and automatic staking unlocked by system, I do not unstake, the power still 2x even though the staking is not locked

Macbook Pro with operating system macOS Big Sur 11.0.1, Browser Google Chrome for mac Version Version 87.0.4280.88 (Official Build) (x86_64), time checking 22.35 until 23.00 WIB 13-12-2020

Thank you

Best regards

Hamron Hamada

**Comment by ngkong** [comment]
it is intended to be that way, power will remain the same unless you unstake your stake

**Comment by HamronHamada** [comment]
Hi admin... my LP staking is unlocked automatically by system after 1 month period is over, now my power staking got 2X power although my status is unlocked and I can unstake at any time

regrads
